name: flutter_package_browser
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  go_router: ^13.1.0
  http: ^1.2.2
  freezed_annotation: ^3.1.0
  url_launcher: ^6.3.1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5

  test: ^1.25.15
  mocktail: ^1.0.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

